### ISSUE TITLE
Your kernel headers for kernel 5.17.0-1020-oem cannot be found.

### ISSUE THREAD

**Issue by fsilly** [cilynx/rtl88x2bu#231]
Hi I am trying to install this driver on my machine but I encountered this error during dkms build and I don't know how to solve it. Thanks!

Error! Your kernel headers for kernel 5.17.0-1020-oem cannot be found.
Please install the linux-headers-5.17.0-1020-oem package or use the --kernelsourcedir option to tell DKMS where it's located.
nyasoftware@nyasoftware-System-Product-Name:~/

**Comment by nye0** [comment]
I have the similar issue in raspberrypi. 
Here is my error message:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/66538912/198518486-04102f91-9590-4d56-940d-660f4b2ee4e4.png">
```
Your kernel headers for kernel 5.4.83-v7+ cannot be found at
/lib/modules/5.4.83-v7+/build or /lib/modules/5.4.83-v7+/source.
```
Just solved by
```
sudo dkms remove rtl88x2bu/${VER} --all
rm -rf /usr/src/rtl88x2bu-${VER}
sudo apt install --reinstall raspberrypi-kernel raspberrypi-kernel-headers
```
I think reason may because the kernel is not updated to the last one.
[ref](https://github.com/aircrack-ng/rtl8812au/issues/717)

**Comment by onlize** [comment]
I have the following error message:
`
     pi@raspberrypi:~ $ ls
     rtl8812au
`
     pi@raspberrypi:~ $ sudo dkms remove rtl88x2bu/${VER} --all
     Error! Arguments <module> and <module-version> are not specified
     Usage: remove <module>/<module-version> or
            remove -m <module>/<module-version> or
           remove -m <module> -v <module-version>
     pi@raspberrypi:~ $
`

**Comment by MaxG87** [comment]
Hi @onlize , have you set the `${VER}` shell variable? Your snippet lets me suspect it is unset. In order to remove all driver modules, I use `sudo dkms remove -m rtl88x2bu -v 5.8.7.1 --all`, which works without any variables. Since the version virtually never changes, there is no need to keep the snippet flexible.

**Comment by MaxG87** [comment]
While here, I need to add that the above mentioned trick does not work for me. I am on Raspbian, with Kernel `6.1.21-v8+` and albeit I ran `sudo apt install --reinstall raspberrypi-kernel raspberrypi-kernel-headers` I still cannot compile the driver module!
